name: "fraud_detection"
version: "1.0.0"
config-version: 2

profile: "fraud_detection"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fraud_detection:
    sources:
      +materialized: source
    staging:
      +materialized: materialized_view
    fraud_signals:
      +materialized: materialized_view
    risk_aggregations:
      +materialized: materialized_view
    case_management:
      +materialized: materialized_view
