apiVersion: 1

datasources:
  - name: RisingWave
    uid: risingwave
    type: grafana-postgresql-datasource
    url: risingwave:4566
    database: dev
    user: root
    secureJsonData:
      password: ''
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: false
